baseURL = 'https://jjgroenendijk.nl'
languageCode = 'en-us'
title = 'jjgroenendijk.nl'
theme = 'hugo-book'
enableGitInfo = true

[params]
    BookRepo = 'https://github.com/jjgroenendijk/jjgroenendijk.github.io'
    BookCommitPath = 'commit'
    BookEditPath = 'edit/main'
    BookSection = '*'

[menu]
#  title = 'Links'
#[[menu.before]]
#  name = "Links"
[[menu.after]]
  name = "Github"
  url = "https://github.com/jjgroenendijk"
  weight = 10

[[menu.after]]
  name = "Recipes"
  url = "https://recipe.jjgroenendijk.nl/"
  weight = 20
